function [AE, Error, EncoderOutput] = LBPGFAutoEncoder(Gpoints, LBPpoints, Gpoints1, LBPpoints1, epochs, hiddenLayerG, hiddenLayerL, hiddenLayerG1, hiddenLayerL1, hiddenLayerC)
    GPAutoencoder = trainAutoencoder(Gpoints, hiddenLayerG,...
    'MaxEpochs', epochs,...
    'L2WeightRegularization', 0.001, ...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.05, ...
    'DecoderTransferFunction','purelin');

    LBPAutoencoder = trainAutoencoder(LBPpoints, hiddenLayerL,...
    'MaxEpochs', epochs,...
    'L2WeightRegularization', 0.001, ...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.05, ...
    'DecoderTransferFunction','purelin');

    GPAutoencoder1 = trainAutoencoder(Gpoints1, hiddenLayerG1,...
    'MaxEpochs', epochs,...
    'L2WeightRegularization', 0.001, ...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.05, ...
    'DecoderTransferFunction','purelin');

    LBPAutoencoder1 = trainAutoencoder(LBPpoints1, hiddenLayerL1,...
    'MaxEpochs', epochs,...
    'L2WeightRegularization', 0.001, ...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.05, ...
    'DecoderTransferFunction','purelin');
    
    Gp = encode(GPAutoencoder, Gpoints);
    Lp = encode(LBPAutoencoder, LBPpoints);
    Gp1 = encode(GPAutoencoder1, Gpoints1);
    Lp1 = encode(LBPAutoencoder1, LBPpoints1);
    Cp = vertcat(Gp,Lp, Gp1, Lp1);
    Cp = myColShuffle(Cp);
    
    AE = trainAutoencoder(Cp, hiddenLayerC,...
    'MaxEpochs', epochs,...
    'L2WeightRegularization', 0.001, ...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.05, ...
    'DecoderTransferFunction','purelin');
    
    Error = [mse(predict(GPAutoencoder, Gpoints)-Gpoints),...
        mse(predict(LBPAutoencoder, LBPpoints)-LBPpoints),...
        mse(predict(GPAutoencoder1, Gpoints1)-Gpoints1),...
        mse(predict(LBPAutoencoder1, LBPpoints1)-LBPpoints1),...
        mse(predict(AE, Cp)-Cp),...
        ];
    EncoderOutput = encode(AE, Cp);
end